### ISSUE TITLE
Boot Time

### ISSUE THREAD

**Issue by MuttakinHasib** [0dragosh/hackintosh-ryzen-x570-aorus-ultra#1]
hey, How long does it take to Boot ?

I don't know why mine is 2.02 minutes.
can you please check my EFI ? 
https://github.com/MuttakinHasib/ryzentosh-EFI

**Comment by 0dragosh** [comment]
It boots pretty fast, normal I'd say.

I would suggest you join the AMD Hackintosh Discord server https://discord.gg/EfCYAJW
